FROM dunglas/frankenphp:php8.2-bookworm AS php-dependencies

WORKDIR /app

# Extensiones necesarias para Laravel
RUN install-php-extensions \
    pdo_mysql \
    bcmath \
    exif \
    pcntl \
    intl \
    zip \
    gd

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Archivos de Composer
COPY composer.json composer.lock ./

#
RUN composer install \
    --no-dev \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader \
    --no-scripts

# Verificar que WireUI realmente fue instalado
RUN test -f /app/vendor/wireui/wireui/tailwind.config.js

FROM node:24-bookworm AS frontend

WORKDIR /app


COPY package.json package-lock.json ./

# Instalar dependencias Node
RUN npm ci


COPY resources ./resources
COPY public ./public
COPY vite.config.js ./
COPY tailwind.config.js ./
COPY postcss.config.js ./


COPY --from=php-dependencies /app/vendor ./vendor

# Comprobar WireUI antes de ejecutar Vite
RUN test -f /app/vendor/wireui/wireui/tailwind.config.js


RUN npm run build



FROM dunglas/frankenphp:php8.2-bookworm AS production

WORKDIR /app

# Extensiones necesarias para Laravel
RUN install-php-extensions \
    pdo_mysql \
    bcmath \
    exif \
    pcntl \
    intl \
    zip \
    gd

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

COPY --from=php-dependencies /app/vendor ./vendor

COPY --from=frontend /app/public/build ./public/build

RUN mkdir -p \
    storage/framework/cache \
    storage/framework/sessions \
    storage/framework/views \
    storage/logs \
    bootstrap/cache

# Permisos
RUN chown -R www-data:www-data \
    storage \
    bootstrap/cache

RUN chmod -R 775 \
    storage \
    bootstrap/cache

RUN php artisan package:discover --ansi

RUN composer dump-autoload \
    --no-dev \
    --optimize

ENV APP_ENV=production
ENV APP_DEBUG=false

ENV SERVER_NAME=:80

EXPOSE 80

CMD ["sh", "-c", "frankenphp php-server --root public --listen :${PORT:-80}"]
