databases:
  - name: inventario-db
    plan: free
    databaseName: inventario
    user: inventario_admin

services:
  - type: web
    name: inventario-web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Inventario
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: "base64:9zsVb5+YgPvilBv6Qq52+4Q2WpOIwwqrDaR4l886XWc="
      - key: APP_URL
        value: https://inventario-web-cmvi.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: inventario-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: inventario-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: inventario-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: inventario-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: inventario-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_CHANNEL
        value: stderr
